---
  - name: load os specific vars
    include_vars: "{{ item }}"
    tags:
      - net-ddclient
    with_first_found:
      - files:
        - "{{ ansible_os_family }}.yml"
        - "main.yml"

  - name: install ddclient
    package:
      name: "{{ item }}"
      state: present
    with_items: "{{ net_ddclient_packages }}"
    notify: enable ddclient
    tags:
      - net-ddclient
      - install

  - name: configure ddclient
    template:
      src: "{{ net_ddclient_config_file_src }}"
      dest: "{{ net_ddclient_config_file_dest }}"
      owner: "{{ net_ddclient_config_file_owner }}"
      group: "{{ net_ddclient_config_file_group }}"
      mode: "{{ net_ddclient_config_file_mode }}"
    notify: restart ddclient
    tags:
      - net-ddclient
      - update
